server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/akalanka95/config-repo/
          searchPaths: lectureservice


